#name = input("What is your name? ")
#age = int(input("How old are you? "))
#trueOrFalse = bool(input("Is the input truthy? "))
#print("My name is " + str(name))
#print("I will be " + str(age + 1) + " next year")
#print(trueOrFalse)
#print("The input was converted to " + str(trueOrFalse))

first_name = input("What's your first name? ")
neighbor_fn = input("What's your neighbor's first name? ")
month_you = int(input("How many months have you been coding? "))
month_neighbor = int(input("How many months has your neighbor been coding? "))

print("You are " + first_name + " and you have " + str(month_you) + " months coding experience.")
print("Your neighbor is " + neighbor_fn + " and he/she has " + str(month_neighbor) + " months coding experience.")
